model:
  name: efficientnet_b0
  output_dim: 10

train:
  epochs: 100
  batch_size: 64
  lr: 0.005
  optimizer: adam
  weight_decay: 0.0001
  scheduler:
    type: CosineAnnealingLR
    T_max: 100

dataset:
  name: cifar10
  root: data/cifar10/raw
  train_split: train
  test_split: test
  seed: 42

save:
  path: results/centralized/efficientnet/