model:
  name: efficientnet_b0
  output_dim: 9

train:
  strategy: fedavg
  rounds: 22
  local_epochs: 5
  batch_size: 32
  lr: 0.001
  optimizer: adam
  clients_per_round: 30

fl:
  fraction_fit: 0.4
  min_fit_clients: 12
  min_available_clients: 12

dataset:
  name: custom9
  root: data/train/raw
  split_path: data/split/client30.json
