model:
  name: resnet50
  output_dim: 9

train:
  strategy: fedbn
  rounds: 50
  local_epochs: 5
  batch_size: 32
  lr: 0.001
  optimizer: adam
  clients_per_round: 5

fl:
  fraction_fit: 1.0
  min_fit_clients: 5
  min_available_clients: 5

dataset:
  name: custom9
  root: data/train/raw
  split_path: data/split/dirichlet_alpha5.json

fedbn:
  freeze_bn: true
