model:
  output_dim: 9

train:
  strategy: moon
  rounds: 50
  local_epochs: 5
  batch_size: 32
  lr: 0.001
  optimizer: adam
  clients_per_round: 5
  mu_base: 0.1              # FedProx term
  contrastive_weight: 1.0   # Î»

fl:
  fraction_fit: 1.0
  min_fit_clients: 5
  min_available_clients: 5

moon:
  memory_size: 1
  bn_drift_control:
    enabled: false
