dataset:
  name: custom9                 # 9‑class dataset identifier
  root: data/train/raw
  split:
    type: dirichlet             # Dirichlet partitioning
    alpha: 10.0                 # Medium α → moderate non-IID
    num_clients: 5
    seed: 42
    cache: true                 # Cache split indices on disk